### ISSUE TITLE
where documentation?

### ISSUE THREAD

**Issue by skunkmommy** [awayfl/awayfl-player#14]
Seriously this has like no documentation where is it

**Comment by poudink** [comment]
If you just want to know how to use this thing then I can tell you that much at least.
1. Insall yarn and npm
2. `git clone https://github.com/awayfl/awayfl-player.git`
3. `cd awayfl-player`
4. `yarn`
5. Stick your SWFs in /src/assets/
6. Add entries for the SWFs you added in awayfl.config.js (in the fileconfigs portion).
7. `npm run build`
After this, you'll have a neat little html file for each of your SWFs in /bin/. You can just open them in your browser and they'll work (hopefully).
EDIT: Oh right you should definitely clone the dev branch rather than the master branch, by the way. master's really old.

**Comment by ScratchyGamer314** [comment]
thank you!
